name: Build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@26b0ec14cb23fa6904739307f278c14f94c95bf1 # v5.4.0
      with:
        dotnet-version: |
          8.0.x
          10.0.x
    - name: Build Reason
      run: "echo ref: ${{github.ref}} event: ${{github.event_name}}"
    - name: Build Version
      run: |
        dotnet tool install --global minver-cli --version 7.0.0
        version=$(minver --tag-prefix v)
        echo "MINVERVERSIONOVERRIDE=$version" >> $GITHUB_ENV
    - name: Build
      run: dotnet build --configuration Release
    - name: Run Tests
      run: dotnet test --configuration Release --no-build
    - name: Package
      if: github.event_name != 'pull_request'
      run: dotnet pack --configuration Release --no-build
    - name: Publish CI Packages
      if: github.event_name != 'pull_request' && github.repository == 'titarenko/OAuth2'
      run: |
        for package in $(find -name "*.nupkg" | grep "minver" -v); do
          echo "${0##*/}": Pushing $package...

          # GitHub
          dotnet nuget push $package --source https://nuget.pkg.github.com/titarenko/index.json --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate
        done
    - name: Publish Release Packages
      if: startsWith(github.ref, 'refs/tags/v') && github.repository == 'titarenko/OAuth2'
      run: |
        for package in $(find -name "*.nupkg" | grep "minver" -v); do
          echo "${0##*/}": Pushing $package...
          dotnet nuget push $package --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_KEY }} --skip-duplicate
        done
